### PR TITLE
Get the order object from the completeCheckout callback

### LINKED ISSUE #21: Get the order id once the checkout is completed
Hi there,

I'm using your bridge for a little while now (huge thanks!), and everything has worked well so far.
I was able to complete a native checkout, but i'd like to edit an order once the checkout has been completed (in order to add some `note_attributes` to that order with their API).

My question is: is it possible to get the order data (I'd just need the id) from the callback of the `completeCheckout` method? I'm assuming that's somehow related to [those lines](https://github.com/shoutem/react-native-shopify/blob/master/ios/RNShopify.m#L210-L211), but my knowledge of iOS development is now quite limited.

Any thoughts?

### PR DESCRIPTION
**Pull request by jgrancher**
Resolves #21 :)

### CODE REVIEW

**Comment by Air-Miha** [comment]
Thanks for the PR!

What do you think about passing the entire order and not just ID? @SoHotSoup, feel free to chime in.

**Comment by SoHotSoup** [comment]
I agree with @Air-Miha it would be useful to have whole order object in resolve callback.

**Comment by jgrancher** [comment]
@Air-Miha @SoHotSoup Updated!

**Comment by Air-Miha** [comment]
@jgrancher, looks good!

I remembered one other thing. Can you do the same for Android?

**Comment by jgrancher** [comment]
@Air-Miha I've added a commit... But this is actually my first Java line of code ever, so I guess it'd be more than necessary if someone in your team could triple-check that 😄

**Comment by Air-Miha** [comment]
And, how do you like Java? Your first line of code is good! Did you test this by any chance with your application? 

Btw, will your application support Android? Everything should work out of the box.

**Comment by jgrancher** [comment]
Well it was alright, surprisingly painless. ;)
Didn't have the opportunity to try that on my app though, as i'm only developing it for iOS for now!

**Comment by jgrancher** [comment]
Hey @Air-Miha,
Would you be able to push that to npm? (minor bump, maybe?)
Thanks!

**Comment by Air-Miha** [comment]
@jgrancher,

I published 0.2.3. We squeezed in another small fix ;).

**Pull request merged**
